### PR TITLE
Added function "getParameterValue" to return value of any given variable name.

### PR DESCRIPTION
**Pull request by Zarnack**
See issue #4

### CODE REVIEW

**Comment by ralph-lange** [comment]
Thank you for this pull request, @Zarnack. Unfortunately, it is very difficult for me to review your changes as the whole code has been reformatted (probably by your IDE). Also, it does no longer meet the ROS 2 code style, which is checked here automatically by ament_uncrustify. Can you please redo the changes without reformatting the whole code or restore the original formatting, for which `ament_uncrustify --reformat` is very handy.

**Comment by Zarnack** [comment]
I fixed all the formatting issues (which indeed have been caused by my IDE).
Thank you for your pointer to `ament_uncrustify --reformat`.

About the origin pull request:
I just added the function `getParamaterValue` which is similar to `getOuptutValue` but without checking if the given variable is of type _output_.

**Comment by ralph-lange** [comment]
Thank you for updating the PR. Regarding the name of the new function: Is there a specific reason why you called it `getParameterValue` and not simply `getValue`? Are you using the new function for (fixed) parameters only?

**Comment by Zarnack** [comment]
There is no specific reason. I just always used the name _parameter_ instead of _value_. 
I will change the name to `getValue`

**Review by ralph-lange — APPROVED** [review]
Thank you very much, @Zarnack

**Pull request merged**
